<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WarehouseERP.Application\WarehouseERP.Application.csproj" />
    <ProjectReference Include="..\WarehouseERP.Infrastructure\WarehouseERP.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="host.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="local.settings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.52.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.1.0" />
  </ItemGroup>

</Project>
